### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by asapverneri** [destoer/Cs2Jailbreak#2]
Hi,

I downloaded newest release and it crashes the server. 
CSSharp v126

Console error:
```
invalid counterterrorist spawnpoint at (-385.4,-1359.9,67.5)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at CounterStrikeSharp.API.Core.Helpers.InvokeNative(IntPtr)
--------------------------------
   at CounterStrikeSharp.API.Core.ScriptContext.InvokeNativeInternal()
   at CounterStrikeSharp.API.Core.ScriptContext.Invoke()
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, System.Object[])
   at CounterStrikeSharp.API.Modules.Memory.VirtualFunction+<>c__DisplayClass2_0`1[[System.IntPtr, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<CreateVoid>b__1(IntPtr)
   at CounterStrikeSharp.API.Core.CCSPlayer_ItemServices.RemoveWeapons()
   at CounterStrikeSharp.API.Core.CCSPlayerController.RemoveWeapons()
   at Lib.strip_weapons(CounterStrikeSharp.API.Core.CCSPlayerController, Boolean)
   at Warden.setup_player_guns(CounterStrikeSharp.API.Core.CCSPlayerController)
   at Warden.spawn(CounterStrikeSharp.API.Core.CCSPlayerController)
   at JailPlugin+<>c__DisplayClass30_0.<OnPlayerSpawn>b__0()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.FunctionReference+<>c__DisplayClass3_0.<.ctor>b__0(CounterStrikeSharp.API.Core.fxScriptContext*)
```

**Comment by destoer** [comment]
Im having some computer trouble atm but i will have a look when i solve it. i havent tested it on the new cs update, what is your OS that the server is on just for interest?

**Comment by asapverneri** [comment]
> Im having some computer trouble atm but i will have a look when i solve it. i havent tested it on the new cs update, what is your OS that the server is on just for interest?

Im running windows server 2022 if i remember correctly. No rush or anything.

**Comment by destoer** [comment]
Theres been issues with remove weapons on windows before

**Comment by destoer** [comment]
the offending crashing code has been gated in a recent patch (NOTE: this does not mean the plugin works properly, just that it no longer crashes)

1) Remove weapons, which i believe is a signature issue https://github.com/roflmuffin/CounterStrikeSharp/issues/250
2) OnTakeDamage hook doesn't work on any plugins, the exact cause of this is not known at present

**Comment by destoer** [comment]
Remove weapons is now fixed, unsure on OnTakeDamage status
