### ISSUE TITLE
Startup Exceptions

### ISSUE THREAD

**Issue by xpara97** [destoer/Cs2Jailbreak#3]
Ubuntu 22.04, dockered CS2 Gameserver
CSSharp 126

Appears on startup:

```
14:10:52 [INFO] (cssharp:PluginContext) Loading plugin Cs2Jailbreak
15:10:53
14:10:53 [EROR] (cssharp:PluginManager) Failed to load plugin from /AMP/counter-strike2/730/game/csgo/addons/counterstrikesharp/plugins/Cs2Jailbreak/Cs2Jailbreak.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 989
at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
at JailPlugin.register_hook() in /mnt/BEEG/cs2_ds/game/csgo/addons/counterstrikesharp/scripting/Cs2Jailbreak/src/Jail.cs:line 256
at JailPlugin.Load(Boolean hotReload) in /mnt/BEEG/cs2_ds/game/csgo/addons/counterstrikesharp/scripting/Cs2Jailbreak/src/Jail.cs:line 153
at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 201
at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34
```

**Comment by destoer** [comment]
NOTE: appears to happen when weaponpaints its running alongside jb
